In [ ]:
!gdown --id "18XTimWqULXDmBrSVQ1GxUkx3L52w7Rbd" -O "data.csv"

Downloading...
From: https://drive.google.com/uc?id=18XTimWqULXDmBrSVQ1GxUkx3L52w7Rbd
To: /content/data.csv
100% 45.8M/45.8M [00:00<00:00, 185MB/s]


In [ ]:
!pip install transformers

     |████████████████████████████████| 3.8 MB 5.1 MB/s 
     |████████████████████████████████| 596 kB 42.4 MB/s 
     |████████████████████████████████| 895 kB 42.5 MB/s 
     |████████████████████████████████| 6.5 MB 32.1 MB/s 
     |████████████████████████████████| 67 kB 3.6 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
import os
use_tpu = True #@param {type:"boolean"}

if use_tpu:
    assert 'COLAB_TPU_ADDR' in os.environ, 'Missing TPU; did you request a TPU in Notebook Settings?'

if 'COLAB_TPU_ADDR' in os.environ:
  TF_MASTER = 'grpc://{}'.format(os.environ['COLAB_TPU_ADDR'])
else:
  TF_MASTER=''

In [ ]:
import tensorflow as tf

resolver = tf.distribute.cluster_resolver.TPUClusterResolver(TF_MASTER)
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)

INFO:tensorflow:Deallocate tpu buffers before initializing tpu system.


INFO:tensorflow:Deallocate tpu buffers before initializing tpu system.


INFO:tensorflow:Initializing the TPU system: grpc://10.27.159.234:8470


INFO:tensorflow:Initializing the TPU system: grpc://10.27.159.234:8470


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


In [ ]:
import pandas as pd
import numpy as np


df = pd.read_csv("data.csv")
df = df.sample(frac=1).reset_index(drop=True)

df.head()

Message  Label
0  dow before we continue very important it is ex...      1
1  men s health viagra cialis levitra anti depres...      1
2  in october of this year we asked you to partic...      0
3  from the desk of mr adnan a k ismail manager n...      1
4  louise here s what we ve got this list of mtm ...      0

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(list(df["Message"].values), list(df["Label"].values), test_size = 0.1, random_state = 42)

In [ ]:
from transformers import DistilBertTokenizerFast

# Instantiate DistilBERT tokenizer...we use the Fast version to optimize runtime
tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/483 [00:00<?, ?B/s]

In [ ]:
input_training = tokenizer(X_train, truncation = True, padding = True)
input_validation = tokenizer(X_valid, truncation = True, padding = True)

In [ ]:
input_training_tensor = tf.data.Dataset.from_tensor_slices((dict(input_training), np.array(y_train).reshape(-1, 1)))
input_validation_tensor = tf.data.Dataset.from_tensor_slices((dict(input_validation), np.array(y_valid).reshape(-1, 1)))

In [ ]:
tokenizer.save_vocabulary(os.path.join(os.getcwd()))

('/content/vocab.txt',)

In [ ]:
for data, target in input_training_tensor.take(1):
    print(data)
    print(target)

{'input_ids': <tf.Tensor: shape=(512,), dtype=int32, numpy=
array([  101,  5310,  5653,  8758, 23651,  3039,  4471,  4175,  2396,
        1998, 11048,  5653,  2372,  1058,  2538,  2522,  2866,  2434,
        4471,  4076,  2363,  2013, 15488, 25856, 29215,  2078, 12170,
        2480,  6640, 24194,  7558, 14168,  2011,  5653,  2372,  1058,
        2538,  2522,  2866,  2007,  9686, 20492,  2361, 15488, 25856,
        2094,  3590,  1022,  4002,  8909, 21358,  1017, 12935,  1020,
        1037,  3770, 12521,  2620, 10722,  2063,  2539, 21650,  2384,
        2260,  5511,  4008,  5890,  8889,  2363,  2013,  7479, 10093,
       20984,  4012,  6640, 24194,  7558,  1023,  2011, 15488, 25856,
       29215,  2078, 12170,  2480,  2007,  9686, 20492,  2361,  4654,
        5714,  1018,  4724,  8909, 25510,  6279, 11631,  2199,  2549,
       14161, 19817,  2005,  2396,  1998, 11048,  2372,  1058,  2538,
        2522,  2866, 10722,  2063,  2539, 21650,  2384,  2340,  5388,
        4749,  5890,  8889,  2

In [ ]:
def build_model(transformer, max_length = 512):
    """""""""
    Template for building a model off of the BERT or DistilBERT architecture
    for a binary classification task.
    
    Input:
      - transformer:  a base Hugging Face transformer model object (BERT or DistilBERT)
                      with no added classification head attached.
      - max_length:   integer controlling the maximum number of encoded tokens 
                      in a given sequence.
    
    Output:
      - model:        a compiled tf.keras.Model with added classification layers 
                      on top of the base pre-trained model architecture.
    """""""""
    
    # Define weight initializer with a random seed to ensure reproducibility
    weight_initializer = tf.keras.initializers.GlorotNormal(seed=RANDOM_STATE) 
    
    # Define input layers
    input_ids_layer = tf.keras.layers.Input(shape=(max_length,), 
                                            name='input_ids', 
                                            dtype='int32')
    input_attention_layer = tf.keras.layers.Input(shape=(max_length,), 
                                                  name='attention_mask', 
                                                  dtype='int32')
    
    # DistilBERT outputs a tuple where the first element at index 0
    # represents the hidden-state at the output of the model's last layer.
    # It is a tf.Tensor of shape (batch_size, sequence_length, hidden_size=768).
    last_hidden_state = transformer(input_ids_layer, input_attention_layer)[0]
    
    # We only care about DistilBERT's output for the [CLS] token, 
    # which is located at index 0 of every encoded sequence.  
    # Splicing out the [CLS] tokens gives us 2D data.
    cls_token = tf.keras.layers.Lambda(lambda x: x[:, 0, :])(last_hidden_state)
    
    x = tf.keras.layers.Dense(256, activation = "relu", kernel_initializer=weight_initializer)(cls_token)
    x = tf.keras.layers.Dropout(0.2)(x)
    x = tf.keras.layers.Dense(32, activation = "relu", kernel_initializer=weight_initializer)(x)
    x = tf.keras.layers.Dropout(0.2)(x)
    
    # Define a single node that makes up the output layer (for binary classification)
    output = tf.keras.layers.Dense(1, 
                                   activation='sigmoid',
                                   kernel_initializer=weight_initializer,  
                                   kernel_constraint=None,
                                   bias_initializer='zeros'
                                   )(x)
    
    # Define the model
    model = tf.keras.Model([input_ids_layer, input_attention_layer], output)
    
    # Compile the model
    model.compile(tf.keras.optimizers.Adam(learning_rate = LEARNING_RATE), 
                  loss="binary_crossentropy",
                  metrics=['accuracy'])
    
    return model

In [ ]:
from transformers import TFDistilBertModel, DistilBertConfig

MAX_LENGTH = 512
LAYER_DROPOUT = 0.2
# (the authors of the original BERT paper recommend learning rates of 3e-4, 1e-4, 5e-5, and 3e-5 as good starting points)
LEARNING_RATE = 5e-5
RANDOM_STATE = 42

with strategy.scope():

    DISTILBERT_DROPOUT = 0.2
    DISTILBERT_ATT_DROPOUT = 0.2
    
    # Configure DistilBERT's initialization
    config = DistilBertConfig(dropout=DISTILBERT_DROPOUT, 
                            attention_dropout=DISTILBERT_ATT_DROPOUT, 
                            output_hidden_states=True)
                            
    # The bare, pre-trained DistilBERT transformer model outputting raw hidden-states 
    # and without any specific head on top.
    distilBERT = TFDistilBertModel.from_pretrained('distilbert-base-uncased', config=config)

    # Make DistilBERT layers untrainable
    # for layer in distilBERT.layers[-2:]:
    #     layer.trainable = False
    model = build_model(distilBERT)
model.summary()

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertModel: ['vocab_transform', 'vocab_projector', 'activation_13', 'vocab_layer_norm']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 512)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 512)]        0           []                               
                                                                                                  
 tf_distil_bert_model_5 (TFDist  TFBaseModelOutput(l  66362880   ['input_ids[0][0]',              
 ilBertModel)                   ast_hidden_state=(N               'attention_mask[0][0]']         
                                one, 512, 768),                                                   
                                 hidden_states=((No                                         

In [ ]:
EPOCHS = 2
BATCH_SIZE = 32
NUM_STEPS = len(X_train) // BATCH_SIZE

# Train the model
train_history1 = model.fit(
    input_training_tensor.batch(BATCH_SIZE),
    epochs = EPOCHS,
    # batch_size = BATCH_SIZE,
    # steps_per_epoch = NUM_STEPS,
    validation_data = input_validation_tensor.batch(BATCH_SIZE),
    verbose=1
)

Epoch 1/2
1120/1120 [==============================] - 204s 134ms/step - loss: 0.0858 - accuracy: 0.9675 - val_loss: 0.0291 - val_accuracy: 0.9910
Epoch 2/2
1120/1120 [==============================] - 104s 93ms/step - loss: 0.0263 - accuracy: 0.9915 - val_loss: 0.0409 - val_accuracy: 0.9889


In [ ]:
model.evaluate(input_validation_tensor)

3980/3980 [==============================] - 84s 20ms/step - loss: 0.0776 - accuracy: 0.9822


[0.07757413387298584, 0.9821608066558838]

In [ ]:
model.save("model_tpu")

INFO:tensorflow:Assets written to: model_tpu/assets


INFO:tensorflow:Assets written to: model_tpu/assets


UnimplementedError: ignored

In [ ]:
model.predict(dict(tokenizer("Hi Rudresh Here, nice to meet you!", padding = "max_length", return_tensors = 'tf')))

array([[0.00152478]], dtype=float32)

In [ ]:
model.save_weights(os.path.join(os.getcwd(), 'weights.h5'), overwrite=True)

Saving model trained on TPU is causing some problems while loading model back in memory   
Another approach in my mind is that we can save weigths of TPU model and load that to a CPU model

In [ ]:
# load model in CPU

# Configure DistilBERT's initialization
config = DistilBertConfig(dropout=DISTILBERT_DROPOUT, 
                        attention_dropout=DISTILBERT_ATT_DROPOUT, 
                        output_hidden_states=True)
                        
# The bare, pre-trained DistilBERT transformer model outputting raw hidden-states 
# and without any specific head on top.
distilBERT = TFDistilBertModel.from_pretrained('distilbert-base-uncased', config=config)

# Make DistilBERT layers untrainable
for layer in distilBERT.layers:
    layer.trainable = False
model_loaded = build_model(distilBERT)
model_loaded.load_weights("weights.h5")

Some layers from the model checkpoint at distilbert-base-uncased were not used when initializing TFDistilBertModel: ['vocab_transform', 'vocab_projector', 'activation_13', 'vocab_layer_norm']
- This IS expected if you are initializing TFDistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFDistilBertModel were initialized from the model checkpoint at distilbert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [ ]:
model_loaded.predict(dict(tokenizer("Hi Rudresh Here, nice to meet you!", padding = "max_length", return_tensors = 'tf')))

array([[0.00151575]], dtype=float32)

Models is loaded successfully using CPU and performance difference is minuscule, so I'm converting this model to tflite model 

In [ ]:
# export model to tflite
converter = tf.lite.TFLiteConverter.from_keras_model(model_loaded)
converter.experimental_new_converter = True
converter.allow_custom_ops = True
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
]

# For conversion with FP16 quantization
# converter.target_spec.supported_types = [tf.float16]
# converter.optimizations = [tf.lite.Optimize.DEFAULT]
# converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]

tflite_model = converter.convert()
open("distilbert_tpu.tflite", 'wb' ).write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmptzsmykx_/assets


INFO:tensorflow:Assets written to: /tmp/tmptzsmykx_/assets


266421500

## Inference on Tflite Model

Now lets run inference on tflite model to check whether it's working as expected

In [ ]:
# Load TFLite model and see some details about input/output

tflite_interpreter = tf.lite.Interpreter(model_path="/content/distilbert_tpu.tflite")

input_details = tflite_interpreter.get_input_details()
output_details = tflite_interpreter.get_output_details()

print("name:", input_details[0]['name'])
print("shape:", input_details[0]['shape'])
print("type:", input_details[0]['dtype'])

print("\n== Output details ==")
print("name:", output_details[0]['name'])
print("shape:", output_details[0]['shape'])
print("type:", output_details[0]['dtype'])

name: input_ids
shape: [  1 512]
type: <class 'numpy.int32'>

== Output details ==
name: Identity
shape: [1 1]
type: <class 'numpy.float32'>


In [ ]:
tflite_interpreter.allocate_tensors()

input_details = tflite_interpreter.get_input_details()
output_details = tflite_interpreter.get_output_details()

print("== Input details ==")
print("name:", input_details[0]['name'])
print("shape:", input_details[0]['shape'])
print("type:", input_details[0]['dtype'])

print("name:", input_details[1]['name'])
print("shape:", input_details[1]['shape'])
print("type:", input_details[1]['dtype'])

print("\n== Output details ==")
print("name:", output_details[0]['name'])
print("shape:", output_details[0]['shape'])
print("type:", output_details[0]['dtype'])

== Input details ==
name: input_ids
shape: [  1 512]
type: <class 'numpy.int32'>
name: attention_mask
shape: [  1 512]
type: <class 'numpy.int32'>

== Output details ==
name: Identity
shape: [1 1]
type: <class 'numpy.float32'>


In [ ]:
input_details

[{'dtype': numpy.int32,
  'index': 0,
  'name': 'input_ids',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([  1, 512], dtype=int32),
  'shape_signature': array([ -1, 512], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': numpy.int32,
  'index': 1,
  'name': 'attention_mask',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
   'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32)},
  'shape': array([  1, 512], dtype=int32),
  'shape_signature': array([ -1, 512], dtype=int32),
  'sparsity_parameters': {}}]

In [ ]:
data = dict(tokenizer("Hi Rudresh Here, nice to meet you!", padding = "max_length", return_tensors = 'tf'))
print(data["input_ids"])
print(data["attention_mask"])

tf.Tensor(
[[  101  7632 21766 16200  4095  2182  1010  3835  2000  3113  2017   999
    102     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0  

In [ ]:
tflite_interpreter.set_tensor(input_details[0]['index'], data["input_ids"])
tflite_interpreter.set_tensor(input_details[1]['index'], data["attention_mask"])

tflite_interpreter.invoke()

tflite_model_predictions = tflite_interpreter.get_tensor(output_details[0]['index'])
print("Prediction results shape:", tflite_model_predictions.shape)
print(tflite_model_predictions)

Prediction results shape: (1, 1)
[[0.00151581]]


In [62]:
!wget "https://drive.google.com/uc?export=download&id=1InLsBLhBsUZ_IK6aMJFPaiFrsTAkGo7_&confirm=t" -O model.tflite

--2022-03-19 17:30:35--  https://drive.google.com/uc?export=download&id=1InLsBLhBsUZ_IK6aMJFPaiFrsTAkGo7_&confirm=t
Resolving drive.google.com (drive.google.com)... 173.194.198.100, 173.194.198.138, 173.194.198.102, ...
Connecting to drive.google.com (drive.google.com)|173.194.198.100|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0o-0s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/hont32rqhfe0rgllcdc6er01crshtutg/1647711000000/09722791128690403417/*/1InLsBLhBsUZ_IK6aMJFPaiFrsTAkGo7_?e=download [following]
--2022-03-19 17:30:35--  https://doc-0o-0s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/hont32rqhfe0rgllcdc6er01crshtutg/1647711000000/09722791128690403417/*/1InLsBLhBsUZ_IK6aMJFPaiFrsTAkGo7_?e=download
Resolving doc-0o-0s-docs.googleusercontent.com (doc-0o-0s-docs.googleusercontent.com)... 209.85.146.132, 2607:f8b0:4001:c1f::84
Connecting to doc-0o-0s-docs.googleusercontent.com (

So result is still same after converting to TFlite format, so we can safely transfer this model to Mobile app